### ISSUE TITLE
package.json has unneeded dependencies

### ISSUE THREAD

**Issue by Razzeee** [tonysamperi/generator-ngx-lib#3]
I think it would be nicer, to just include the essentials for this to run. Every user can then build of of that.

With the current implementation I get stuff for mongoDB, jquery etc...

**Comment by tonysamperi** [comment]
Mmm..seems odd...
Which version of angular are you using?

**Comment by tonysamperi** [comment]
Exactly.

So you would remove jQuery, Mongoose ? Anything else?

**Comment by Razzeee** [comment]
I removed from dependencies:
    
- "@3846masa/axios-cookiejar-support": "^0.4.2",
- "@angularclass/hmr": "^2.1.3",
- "angular-froala-wysiwyg": "^2.8.5",
- "bcryptjs": "^2.4.3",
- "jquery": "^3.3.1",
- "qs": "^6.5.2",

Moved this to devDependencies:
- "@types/moment": "^2.13.0",

Removed from devDependencies:
- "@types/express": "^4.16.0",
- "@types/jquery": "^3.3.21",
- "@types/mongoose": "^5.2.19",
- "@types/morgan": "^1.7.35",
- "all-contributors-cli": "^5.4.1",

I kept moments and lodash, but not sure if I will use them at all.

I think I also had to add tsickle to make it build.

**Comment by tonysamperi** [comment]
ok removed lodash and bootstrap as well.
These shouldn't be defaults as well.
