### ISSUE TITLE
Ng lint & test fails

### ISSUE THREAD

**Issue by Razzeee** [tonysamperi/generator-ngx-lib#4]
Due to `tsconfig.spec.json` being expected, but the file was not created.

**Comment by tonysamperi** [comment]
Ok. I actually don't know what to put inside that file.
I'll take a look...

**Comment by Razzeee** [comment]
adding `tsconfig.spec.json` to the `src` folder with this will work
```
{
    "extends": "./tsconfig.lib.json",
    "files": [
        "**/*.spec.ts"
    ]
}
```

not sure if we want more.

But you will get other errors after that for ng lint / ng test.
Ng test is missing the `karma.conf.js` in `src`.
ng lint will bail due to `error TS5058: The specified path does not exist: 'C:\development\WuH\wuh-design\e2e\tsconfig.e2e.json'.`
Not sure why it's trying to get the e2e file.

**Comment by tonysamperi** [comment]
Alright. I'll add this

`{
    "extends": "./tsconfig.lib.json",
    "files": [
        "**/*.spec.ts"
    ]
}
`

And we give it a tsconfig.e2e as well, I'll figure out what to put inside

**Comment by Razzeee** [comment]
Karma config needs to be changed for newer angular version:

```
 Error: In Angular CLI >6.0 the Karma plugin is now exported by "@angular-devkit/build-angular" instead.
Please replace "@angular/cli" with "@angular-devkit/build-angular" in your "karma.conf.js" file.

```

**Comment by tonysamperi** [comment]
Alright. Will fix tonight. 
Will add dedicated karma config for 5 and 6+

**Comment by Razzeee** [comment]
I also had to do this https://stackoverflow.com/a/50426456/2859813

Still having an error probably due to the test files not being included and not being picked up by the glob in `tsconfig.spec.json`

**Comment by tonysamperi** [comment]
I'm removing the `karma.config.js` from versions 6 and 7, since the `angular.json` already has the config.
Users will be able to fine tune their config by creating a `karma.conf.js` (pay attention to the spelling, since this name is in the `angular.json`)
