### ISSUE TITLE
ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead.

### ISSUE THREAD

**Issue by doudbanks** [tonysamperi/generator-ngx-lib#7]
Hi Tony,

Right after the generation, the first npm run build fail because of: 

`ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead.`

It's because of the:

`"typescript": "^3.1.3",`

You should use the tilde instead of the caret in the version number.

`"typescript": "~3.1.3",`

**Comment by tonysamperi** [comment]
Which version of Angular did you choose when generating the project?

**Comment by doudbanks** [comment]
7

Le mer. 13 févr. 2019 à 09:29, Tony Samperi <notifications@github.com> a
écrit :

**Comment by doudbanks** [comment]
Do you use slack ? Could you create a space for your library ?

**Comment by tonysamperi** [comment]
Nope, I think this is more than enough for now.
Usually my libraries never have blocking issues...something like your issue, which you can solve yourself.
Anyway I'll update the package in the source files.

**Comment by doudbanks** [comment]
Ok then, I'm just trying to see the difference between your generator and
the one of the angular-cli, both have 3 folders, lib, src and dist. So
what's the advantage of using yours ? (I'm just trying to figure out which
one to use)

Le mer. 13 févr. 2019 à 09:33, Tony Samperi <notifications@github.com> a
écrit :

**Comment by tonysamperi** [comment]
I'm glad you asked.

1. In mine you keep 1 package.json, with angular-cli there's 2
2. 1 sub-folder less in the "lib" part

Other than that they're basically the same...

**Comment by doudbanks** [comment]
Ok thanks.
